let data_lukisan = [
  {
    id: 1,
    title: "Mona Lisa",
    artist: "Leonardo da Vinci",
    year: 1503,
    style: "Renaissance",
    location: "Louvre Museum",
    description: "Lukisan potret paling terkenal di dunia.",
    price: 860,
    country: "Italy",
  },
  {
    id: 2,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    style: "Post-Impressionism",
    location: "Museum of Modern Art (MoMA)",
    description: "Lukisan pemandangan malam dengan pusaran bintang.",
    price: 920,
    country: "Netherlands",
  },
  {
    id: 3,
    title: "The Last Supper",
    artist: "Leonardo da Vinci",
    year: 1498,
    style: "Renaissance",
    location: "Santa Maria delle Grazie, Milan",
    description: "Menggambarkan perjamuan terakhir Yesus dengan para rasul.",
    price: 750,
    country: "Italy",
  },
  {
    id: 4,
    title: "The Scream",
    artist: "Edvard Munch",
    year: 1893,
    style: "Expressionism",
    location: "National Museum, Oslo",
    description:
      "Menggambarkan sosok yang dilanda kecemasan dengan latar langit merah darah.",
    price: 680,
    country: "Norway",
  },
  {
    id: 5,
    title: "Girl with a Pearl Earring",
    artist: "Johannes Vermeer",
    year: 1665,
    style: "Baroque",
    location: "Mauritshuis, Hague",
    description:
      "Dijuluki 'Mona Lisa dari Utara' karena ekspresinya yang misterius.",
    price: 550,
    country: "Netherlands",
  },
  {
    id: 6,
    title: "Guernica",
    artist: "Pablo Picasso",
    year: 1937,
    style: "Cubism",
    location: "Museo Reina Sofía, Madrid",
    description:
      "Karya anti-perang yang menggambarkan penderitaan akibat pemboman Guernica.",
    price: 890,
    country: "Spain",
  },
  {
    id: 7,
    title: "The Persistence of Memory",
    artist: "Salvador Dalí",
    year: 1931,
    style: "Surrealism",
    location: "Museum of Modern Art (MoMA)",
    description: "Terkenal dengan jam-jam saku yang meleleh di lanskap sepi.",
    price: 450,
    country: "Spain",
  },
  {
    id: 8,
    title: "Water Lilies",
    artist: "Claude Monet",
    year: 1915,
    style: "Impressionism",
    location: "Berbagai museum",
    description:
      "Bagian dari seri lukisan yang menggambarkan taman air Monet di Giverny.",
    price: 600,
    country: "France",
  },
  // Ditambahkan dua lukisan baru:
  {
    id: 9,
    title: "American Gothic",
    artist: "Grant Wood",
    year: 1930,
    style: "Regionalism",
    location: "Art Institute of Chicago",
    description:
      "Lukisan potret seorang petani dan putrinya di depan rumah kecil.",
    price: 400,
    country: "United States",
  },
  {
    id: 10,
    title: "The Birth of Venus",
    artist: "Sandro Botticelli",
    year: 1485,
    style: "Renaissance",
    location: "Uffizi Gallery, Florence",
    description:
      "Menggambarkan dewi Venus muncul dari laut sebagai wanita dewasa.",
    price: 700,
    country: "Italy",
  },
];

export default data_lukisan;
