let data_lukisan = [
  {
    id: 1,
    title: "Mona Lisa",
    artist: "Leonardo da Vinci",
    year: 1503,
    style: "Renaissance",
    location: "Louvre Museum",
    description: "The most famous portrait painting in the world.",
    price: 860,
    country: "Italy",
  },
  {
    id: 2,
    title: "The Starry Night",
    artist: "Vincent van Gogh",
    year: 1889,
    style: "Post-Impressionism",
    location: "Museum of Modern Art (MoMA)",
    description: "A night landscape painting with swirling stars.",
    price: 920,
    country: "Netherlands",
  },
  {
    id: 3,
    title: "The Last Supper",
    artist: "Leonardo da Vinci",
    year: 1498,
    style: "Renaissance",
    location: "Santa Maria delle Grazie, Milan",
    description: "Depicts Jesus' last meal with his apostles.",
    price: 750,
    country: "Italy",
  },
  {
    id: 4,
    title: "The Scream",
    artist: "Edvard Munch",
    year: 1893,
    style: "Expressionism",
    location: "National Museum, Oslo",
    description: "Depicts an agonizing figure against a blood-red sky.",
    price: 680,
    country: "Norway",
  },
  {
    id: 5,
    title: "Girl with a Pearl Earring",
    artist: "Johannes Vermeer",
    year: 1665,
    style: "Baroque",
    location: "Mauritshuis, Hague",
    description:
      "Nicknamed 'the Mona Lisa of the North' due to its mysterious expression.",
    price: 550,
    country: "Netherlands",
  },
  {
    id: 6,
    title: "Guernica",
    artist: "Pablo Picasso",
    year: 1937,
    style: "Cubism",
    location: "Museo Reina Sofía, Madrid",
    description:
      "An anti-war work depicting suffering from the bombing of Guernica.",
    price: 890,
    country: "Spain",
  },
  {
    id: 7,
    title: "The Persistence of Memory",
    artist: "Salvador Dalí",
    year: 1931,
    style: "Surrealism",
    location: "Museum of Modern Art (MoMA)",
    description:
      "Famous for its melting pocket watches in a desolate landscape.",
    price: 450,
    country: "Spain",
  },
  {
    id: 8,
    title: "Water Lilies",
    artist: "Claude Monet",
    year: 1915,
    style: "Impressionism",
    location: "Various museums",
    description:
      "Part of a series of paintings depicting Monet's water garden at Giverny.",
    price: 600,
    country: "France",
  },
  {
    id: 9,
    title: "American Gothic",
    artist: "Grant Wood",
    year: 1930,
    style: "Regionalism",
    location: "Art Institute of Chicago",
    description:
      "A portrait painting of a farmer and his daughter in front of a small house.",
    price: 400,
    country: "United States",
  },
  {
    id: 10,
    title: "The Birth of Venus",
    artist: "Sandro Botticelli",
    year: 1485,
    style: "Renaissance",
    location: "Uffizi Gallery, Florence",
    description:
      "Depicts the goddess Venus emerging from the sea as an adult woman.",
    price: 700,
    country: "Italy",
  },
];

export default data_lukisan;
